//
//  ComprehensiveTestFile.swift
//  Lexing
//
//  Created by Joe Maghzal on 08/11/2025.
//

import Testing
import Foundation
import Diagnostics
@testable import Lexing

enum ComprehensiveTestFile: TestFile {
    static let name = "comprehensive"
    
    static let tokens: [Token] = [
        Token(kind: .keyword(.class), location: SourceLocation(line: 2, column: 1, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 2, column: 7, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 2, column: 12, file: "")),
        Token(kind: .identifier("item"), location: SourceLocation(line: 3, column: 5, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 3, column: 10, file: "")),
        Token(kind: .identifier("Int"), location: SourceLocation(line: 3, column: 12, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 3, column: 15, file: "")),
        Token(kind: .identifier("next"), location: SourceLocation(line: 4, column: 5, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 4, column: 10, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 4, column: 12, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 4, column: 16, file: "")),
        Token(kind: .identifier("init"), location: SourceLocation(line: 6, column: 5, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 6, column: 9, file: "")),
        Token(kind: .identifier("i"), location: SourceLocation(line: 6, column: 10, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 6, column: 12, file: "")),
        Token(kind: .identifier("Int"), location: SourceLocation(line: 6, column: 14, file: "")),
        Token(kind: .comma, location: SourceLocation(line: 6, column: 17, file: "")),
        Token(kind: .identifier("n"), location: SourceLocation(line: 6, column: 19, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 6, column: 21, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 6, column: 23, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 6, column: 27, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 6, column: 29, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 6, column: 31, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 6, column: 36, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 7, column: 9, file: "")),
        Token(kind: .identifier("item"), location: SourceLocation(line: 8, column: 13, file: "")),
        Token(kind: .assign, location: SourceLocation(line: 8, column: 18, file: "")),
        Token(kind: .identifier("i"), location: SourceLocation(line: 8, column: 21, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 8, column: 22, file: "")),
        Token(kind: .identifier("next"), location: SourceLocation(line: 9, column: 13, file: "")),
        Token(kind: .assign, location: SourceLocation(line: 9, column: 18, file: "")),
        Token(kind: .identifier("n"), location: SourceLocation(line: 9, column: 21, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 9, column: 22, file: "")),
        Token(kind: .identifier("self"), location: SourceLocation(line: 10, column: 13, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 10, column: 17, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 11, column: 9, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 12, column: 5, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 12, column: 6, file: "")),
        Token(kind: .identifier("flatten"), location: SourceLocation(line: 14, column: 5, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 14, column: 12, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 14, column: 13, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 14, column: 15, file: "")),
        Token(kind: .identifier("String"), location: SourceLocation(line: 14, column: 17, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 14, column: 24, file: "")),
        Token(kind: .keyword(.let), location: SourceLocation(line: 15, column: 9, file: "")),
        Token(kind: .identifier("string"), location: SourceLocation(line: 15, column: 13, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 15, column: 20, file: "")),
        Token(kind: .identifier("String"), location: SourceLocation(line: 15, column: 22, file: "")),
        Token(kind: .assign, location: SourceLocation(line: 15, column: 29, file: "")),
        Token(kind: .stringLiteral(""), location: SourceLocation(line: 15, column: 32, file: "")),
        Token(kind: .keyword(.in), location: SourceLocation(line: 15, column: 35, file: "")),
        Token(kind: .identifier("string"), location: SourceLocation(line: 16, column: 13, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 17, column: 5, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 17, column: 6, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 18, column: 1, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 18, column: 2, file: "")),
        Token(kind: .keyword(.class), location: SourceLocation(line: 20, column: 1, file: "")),
        Token(kind: .identifier("Main"), location: SourceLocation(line: 20, column: 7, file: "")),
        Token(kind: .keyword(.inherits), location: SourceLocation(line: 20, column: 12, file: "")),
        Token(kind: .identifier("IO"), location: SourceLocation(line: 20, column: 21, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 20, column: 24, file: "")),
        Token(kind: .identifier("main"), location: SourceLocation(line: 21, column: 5, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 21, column: 9, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 21, column: 10, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 21, column: 12, file: "")),
        Token(kind: .identifier("Object"), location: SourceLocation(line: 21, column: 14, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 21, column: 21, file: "")),
        Token(kind: .keyword(.let), location: SourceLocation(line: 22, column: 9, file: "")),
        Token(kind: .identifier("hello"), location: SourceLocation(line: 22, column: 13, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 22, column: 19, file: "")),
        Token(kind: .identifier("String"), location: SourceLocation(line: 22, column: 21, file: "")),
        Token(kind: .assign, location: SourceLocation(line: 22, column: 28, file: "")),
        Token(kind: .stringLiteral("Hello World!\n"), location: SourceLocation(line: 22, column: 31, file: "")),
        Token(kind: .comma, location: SourceLocation(line: 22, column: 47, file: "")),
        Token(kind: .identifier("list"), location: SourceLocation(line: 23, column: 13, file: "")),
        Token(kind: .colon, location: SourceLocation(line: 23, column: 18, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 23, column: 20, file: "")),
        Token(kind: .assign, location: SourceLocation(line: 23, column: 25, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 23, column: 28, file: "")),
        Token(kind: .keyword(.new), location: SourceLocation(line: 23, column: 29, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 23, column: 33, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 23, column: 37, file: "")),
        Token(kind: .dot, location: SourceLocation(line: 23, column: 38, file: "")),
        Token(kind: .identifier("init"), location: SourceLocation(line: 23, column: 39, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 23, column: 43, file: "")),
        Token(kind: .integerLiteral("1"), location: SourceLocation(line: 23, column: 44, file: "")),
        Token(kind: .comma, location: SourceLocation(line: 23, column: 45, file: "")),
        Token(kind: .keyword(.new), location: SourceLocation(line: 23, column: 47, file: "")),
        Token(kind: .identifier("List"), location: SourceLocation(line: 23, column: 51, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 23, column: 55, file: "")),
        Token(kind: .keyword(.in), location: SourceLocation(line: 24, column: 9, file: "")),
        Token(kind: .leftBrace, location: SourceLocation(line: 24, column: 12, file: "")),
        Token(kind: .identifier("out_string"), location: SourceLocation(line: 25, column: 13, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 25, column: 23, file: "")),
        Token(kind: .identifier("hello"), location: SourceLocation(line: 25, column: 24, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 25, column: 29, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 25, column: 30, file: "")),
        Token(kind: .identifier("out_int"), location: SourceLocation(line: 26, column: 13, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 26, column: 20, file: "")),
        Token(kind: .identifier("list"), location: SourceLocation(line: 26, column: 21, file: "")),
        Token(kind: .dot, location: SourceLocation(line: 26, column: 25, file: "")),
        Token(kind: .identifier("item"), location: SourceLocation(line: 26, column: 26, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 26, column: 30, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 26, column: 31, file: "")),
        Token(kind: .identifier("out_string"), location: SourceLocation(line: 27, column: 13, file: "")),
        Token(kind: .leftParen, location: SourceLocation(line: 27, column: 23, file: "")),
        Token(kind: .stringLiteral("\n"), location: SourceLocation(line: 27, column: 24, file: "")),
        Token(kind: .rightParen, location: SourceLocation(line: 27, column: 28, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 27, column: 29, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 28, column: 9, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 29, column: 5, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 29, column: 6, file: "")),
        Token(kind: .rightBrace, location: SourceLocation(line: 30, column: 1, file: "")),
        Token(kind: .semicolon, location: SourceLocation(line: 30, column: 2, file: "")),
        Token(kind: .endOfFile, location: SourceLocation(line: 31, column: 0, file: ""))
    ]
    
    static let diagnostics: [Diagnostic] = []
}
